apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app-deployment
  labels:
    app: nextjs-app
spec:
  replicas: 1 # Recommended for high availability
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs-container
        # !! REPLACE with your actual GHCR image URL !!
        image: ghcr.io/Arfu7860/nextjs-local:latest
        imagePullPolicy: Always # Ensure the latest image is pulled
        ports:
        - containerPort: 3000
        livenessProbe: # Checks if the container is alive
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe: # Checks if the container is ready to serve traffic
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"